const orders = [
  { name: "በየአይነቱ", price: 60, image: "በየአይነቱ.jpg", type: "የጾም" },
  { name: "ሽሮ ፈሰስ", price: 40, image: "ሽሮ ፈሰስ.jpg", type: "የጾም" },
  { name: "እንጀራ ፍርፍር", price: 40, image: "እንጀራ-ፍርፍር.jpg", type: "የጾም" },
  { name: "ተጋቢኖ", price: 50, image: "ተጋቢኖ.jpg", type: "የጾም" },
  {
    name: "አትክልት በእንጀራ",
    price: 50,
    image: "አትክልት-በእንጀራ.jpg",
    type: "የጾም",
  },
  {
    name: "ቲማቲም ስልስ በ2 ዳቦ",
    price: 50,
    image: "ቲማቲም-ስልስ-በ2-ዳቦ.jpg",
    type: "የጾም",
  },
  {
    name: "ፓስታ በአትክልት በ2 ዳቦ",
    price: 55,
    image: "ፓስታ-በአትክልት-በ2-ዳቦ.jpg",
    type: "የጾም",
  },
  { name: "ሩዝ በ2 ዳቦ", price: 50, image: "ሩዝ-በ2-ዳቦ.jpg", type: "የጾም" },
  { name: "ቲማቲም ቁርጥ", price: 45, image: "ቲማቲም ቁርጥ.jpg", type: "የጾም" },
  {
    name: "ሽሮ በቲማቲም ቁርጥ",
    price: 50,
    image: "ሽሮ-በቲማቲም-ቁርጥ.jpg",
    type: "የጾም",
  },
  {
    name: "አትክልት በ2 ዳቦ",
    price: 50,
    image: "አትክልት-በእንጀራ.jpg",
    type: "የጾም",
  },
  {
    name: "ሩዝ በአትክልት ከ2 ዳቦ ጋር",
    price: 50,
    image: "ሩዝ-በ2-ዳቦ.jpg",
    type: "የጾም",
  },
  { name: "ሩዝ በአትክልት ብቻ", price: 40, image: "ሩዝ-በ2-ዳቦ.jpg", type: "የጾም" },
  { name: "ምስር ወጥ", price: 50, image: "ምስር-ወጥ.jpg", type: "የጾም" },
  { name: "ፓስታ በ2 ዳቦ", price: 50, image: "ፓስታ-በ2-ዳቦ.jpg", type: "የጾም" },
  { name: "ፓስታ በእንጀራ", price: 50, image: "ፓስታ-በ2-ዳቦ.jpg", type: "የጾም" },
  { name: "አልጫ ሽሮ", price: 40, image: "አልጫ.ሽሮ.jpg", type: "የጾም" },
  { name: "ድንች ወጥ", price: 45, image: "ድንች-ወጥ.jpg", type: "የጾም" },
  { name: "ሽሮ ፍትፍት", price: 40, image: "ሽሮ-ፍትፍት.jpg", type: "የጾም" },
  {
    name: "ዳቦ ፍርፍር በ2 ዳቦ",
    price: 40,
    image: "ዳቦ-ፍርፍር-በ2-ዳቦ.jpg",
    type: "የጾም",
  },
  {
    name: "መኮረኒ በ2 ዳቦ/በእንጀራ",
    price: 50,
    image: "መኮረኒ-በ2-ዳቦ-በእንጀራ.jpg",
    type: "የጾም",
  },
  { name: "ሙሉ ፍርፍር", price: 55, image: "mulu-rfr.jpg", type: "የጾም" },
  {
    name: "እስፔሻል ፆም ፍርፍር",
    price: 60,
    image: "እስፔሻል-ፆም-ፍርፍር.jpg",
    type: "የጾም",
  },
  { name: "እስፔሻል ሽሮ", price: 50, image: "እስፔሻል-ሽሮ.jpg", type: "የጾም" },
  {
    name: "ቲማቲም ለብለብ",
    price: 50,
    image: "ቲማቲም-ስልስ-በ2-ዳቦ.jpg",
    type: "የጾም",
  },
  {
    name: "ሙሉ ድንች ፍርፍር",
    price: 60,
    image: "ሙሉ ድንች ፍርፍር.jpg",
    type: "የጾም",
  },
  { name: "ሽሮላላ", price: 50, image: "ሽሮላላ.jpg", type: "የጾም" },
  { name: "ድንች ፍርፍር", price: 50, image: "ድንች ፍርፍር.jpg", type: "የፍስግ" },
  { name: "ምስር በድንች", price: 60, image: "ምስር በድንች.jpg", type: "የጾም" },
  { name: "የበሬ ጥብስ", price: 120, image: "የበሬ ጥብስ.jpg", type: "የፍስግ" },
  { name: "እንቁላል በስጋ", price: 110, image: "እንቁላል በስጋ.jpg", type: "የፍስግ" },
  {
    name: "እንቁላል ስልስ 2በዳቦ/እንጀራ",
    price: 80,
    image: "እንቁላል ስልስ 2በዳቦ-እንጀራ.jpg",
    type: "የፍስግ",
  },
  {
    name: "እንቁላል ፍርፍር 2በዳቦ/እንጀራ",
    price: 60,
    image: "እንቁላል ስልስ 2በዳቦ-እንጀራ.jpg",
    type: "የፍስግ",
  },
  {
    name: "እንቁላል ሳንድዊች በ150 ግራምበዳቦ",
    price: 50,
    image: "እንቁላል ሳንድዊች በ150 ግራምበዳቦ.jpg",
    type: "የፍስግ",
  },
  { name: "ድንች በስጋ", price: 75, image: "ድንች በስጋ.jpg", type: "የፍስግ" },
  { name: "ምስር በስጋ", price: 75, image: "", type: "የፍስግ" },
  {
    name: "ሙሉ ስጋ ፍርፍር",
    price: 110,
    image: "ሙሉ ስጋ ፍርፍር.jpg",
    type: "የፍስግ",
  },
  { name: "ስጋ ፍርፍር", price: 90, image: "ስጋ ፍርፍር.jpg", type: "የፍስግ" },
  {
    name: "ፓስታ በእንቁላል በ2 ዳቦ",
    price: 85,
    image: "ፓስታ በእንቁላል በ2 ዳቦ.jpg",
    type: "የፍስግ",
  },
  { name: "ፓስታ በስጋ", price: 90, image: "ፓስታ በስጋ.jpg", type: "የፍስግ" },
  {
    name: "እስፔሻል ስጋ ፍርፍር",
    price: 100,
    image: "እስፔሻል ስጋ ፍርፍር.jpg",
    type: "የፍስግ",
  },
  { name: "ቋንጣ ፍርፍር", price: 100, image: "ቋንጣ ፍርፍር.jpg", type: "የፍስግ" },
  {
    name: "እስፔሻል ቋንጣ ፍርፍር",
    price: 110,
    image: "እስፔሻል ቋንጣ ፍርፍር.jpg",
    type: "የፍስግ",
  },
  { name: "ምንቸት", price: 100, image: "ምንቸት.jpg", type: "የፍስግ" },
  { name: "ቀይ ወጥ", price: 100, image: "ቀይ ወጥ-jpg", type: "የፍስግ" },
  { name: "ሚስቶ", price: 90, image: "ሚስቶ.jpg", type: "የፍስግ" },
  { name: "ሩዝ በስጋ", price: 80, image: "ሩዝ በስጋ.jpg", type: "የፍስግ" },
  { name: "መኮረኒ በስጋ", price: 80, image: "መኮረኒ በስጋ.jpg", type: "የፍስግ" },
];
export default orders;
